import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Amplify, Auth } from "aws-amplify";
import awsExports from "../aws-exports";
import Script from "next/script";
import Providers from "./providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script src="flowbite.min.js" />
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
